/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What this service is. Open without a token, on purpose. */
        get: operations["toWorkspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/canvas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn an instruction into canvas operations.
         * @description The operations come back as the model wrote them. They are validated against the block catalogue on the client, which owns it.
         */
        post: operations["canvas"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** One turn of the folder chat, streamed as newline-delimited JSON. */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/frd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Derive functional requirements from a product requirement document. */
        post: operations["frd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose the concept screens a set of meeting notes implies. */
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether this deployment can call Claude, and which models its aliases mean. */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prove a credential works.
         * @description Runs one tiny Haiku turn. Send X-Anthropic-Api-Key to check your own key rather than the server's.
         */
        post: operations["verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange an email and password for a bearer token.
         * @description Available when this deployment signs its own tokens; 501 when it only verifies tokens from an external issuer.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The account behind the bearer token. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/meetings/{id}/screens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace the set after a generation; unmentioned screens are kept as they are. */
        put: operations["replaceScreens"];
        post?: never;
        /** Reset: the screens go, the notes stay. */
        delete: operations["reset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}/screens/moved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record that the whole set has been sent to a product. */
        post: operations["markMoved"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects; omit `archived` for all of them. */
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
    "/api/projects/{projectId}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        /** Move screens into this product's Request tab. */
        post: operations["move"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** File a waiting request into a round. */
        post: operations["file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screens/{id}/html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The page itself, fetched per screen rather than with the meeting. */
        get: operations["html"];
        /** Save the page. Writing it is what marks the screen modified. */
        put: operations["saveHtml"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything the caller can see, in one read.
         * @description One request rather than one per key: the code that consumes this reads synchronously from inside render paths, so it hydrates once at load. Carries an ETag, so an unchanged workspace costs a 304 and no body.
         */
        get: operations["snapshot"];
        /** Apply a batch of writes and deletions. */
        put: operations["apply"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed only the keys that do not exist yet.
         * @description The one-time handover from a browser that still holds state. Fills gaps and never overwrites, so whichever browser connects first cannot flatten work done from another.
         */
        post: operations["importMissing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Whether this deployment can call Claude at all.
         * @default null
         */
        AiStatus: {
            configured?: boolean;
            defaultModel?: string;
            models?: {
                [key: string]: string;
            };
        };
        /**
         * @description What this call spent.
         * @default null
         */
        AiUsageView: {
            costUsd?: number;
            /** Format: int64 */
            durationMs?: number;
            /** Format: int64 */
            inputTokens?: number;
            model?: string;
            /** Format: int64 */
            outputTokens?: number;
        };
        /** @default null */
        AiVerifyResponse: {
            model?: string;
            ok?: boolean;
        };
        /**
         * @description The screen that exists in production today, when this is a change request rather than a fresh design.
         * @default null
         */
        BaseScreen: {
            blocks?: components["schemas"]["BaseScreenBlock"][];
            path?: string;
            route?: string;
        };
        /**
         * @description One block of the live screen being revised.
         * @default null
         */
        BaseScreenBlock: {
            kind: string;
            label?: string;
        };
        /**
         * @description One block of the canvas being edited.
         * @default null
         */
        CanvasBlockView: {
            hidden?: boolean;
            id: string;
            kind: string;
            name?: string;
            /**
             * @description Catalogue-defined; passed through untouched.
             * @default
             */
            props: {
                [key: string]: unknown;
            };
        };
        /** @default null */
        CanvasEditRequest: {
            blocks: components["schemas"]["CanvasBlockView"][];
            /**
             * @description The block catalogue, rendered by the client. This is what tells the model which kinds and props exist.
             * @default
             */
            catalog: string;
            instruction: string;
            label?: string;
            /**
             * @default null
             * @enum {string}
             */
            model: "opus" | "sonnet" | "haiku" | "opus" | "sonnet" | "haiku";
            /**
             * @description Attributes the spend to a project.
             * @default
             */
            projectId: string;
        };
        /**
         * @description The model's proposed operations, unvalidated against the catalogue — the client checks them before applying.
         * @default null
         */
        CanvasEditResponse: {
            operations?: {
                [key: string]: unknown;
            }[];
            reply?: string;
            usage?: components["schemas"]["AiUsageView"];
        };
        /** @default null */
        ChatAttachment: {
            /**
             * @description Images only — base64 with no data: prefix.
             * @default
             */
            dataBase64: string;
            /** @enum {string} */
            kind: "image" | "text" | "binary";
            mediaType?: string;
            name: string;
            /**
             * @description Text files only — their content, read in the browser.
             * @default
             */
            text: string;
        };
        /** @default null */
        ChatRequest: {
            attachments?: components["schemas"]["ChatAttachment"][];
            context?: string;
            /**
             * @description Thinking depth; ignored by models that do not take it.
             * @default null
             * @enum {string}
             */
            effort: "low" | "medium" | "high" | "xhigh" | "max";
            folderLabel?: string;
            history?: components["schemas"]["ChatTurn"][];
            message: string;
            /**
             * @default null
             * @enum {string}
             */
            model: "opus" | "sonnet" | "haiku" | "opus" | "sonnet" | "haiku";
            projectId?: string;
            projectName?: string;
            /**
             * @description Ask for a reasoning summary; ignored by models without it.
             * @default false
             */
            thinking: boolean;
        };
        /** @default null */
        ChatTurn: {
            /** @enum {string} */
            role: "user" | "assistant";
            text: string;
        };
        /** @default null */
        FrdItem: {
            title?: string;
        };
        /** @default null */
        FrdRequest: {
            /**
             * @default null
             * @enum {string}
             */
            model: "opus" | "sonnet" | "haiku" | "opus" | "sonnet" | "haiku";
            prdDescription?: string;
            prdId: string;
            prdTitle: string;
            projectId?: string;
            requirements: string[];
            screens?: string[];
        };
        /** @default null */
        FrdResponse: {
            items?: components["schemas"]["FrdItem"][];
            reply?: string;
            usage?: components["schemas"]["AiUsageView"];
        };
        /** @default null */
        GeneratedBlock: {
            kind: string;
            /**
             * @description Catalogue-defined; passed through untouched.
             * @default
             */
            props: {
                [key: string]: unknown;
            };
        };
        /** @default null */
        GeneratedScreen: {
            blocks?: components["schemas"]["GeneratedBlock"][];
            name?: string;
            rationale?: string;
            route?: string;
        };
        /** @default null */
        GenerateScreensRequest: {
            baseScreen?: components["schemas"]["BaseScreen"];
            catalog: string;
            customer?: string;
            /** Format: int32 */
            maxScreens?: number;
            /**
             * @default null
             * @enum {string}
             */
            model: "opus" | "sonnet" | "haiku" | "opus" | "sonnet" | "haiku";
            notes: string;
            projectId?: string;
            /**
             * @description Names of attachments with no extractable text, so the model knows they exist.
             * @default
             */
            referenceNames: string[];
            /**
             * @description Merged text of the meeting's reference files.
             * @default
             */
            references: string;
            sessionTitle?: string;
        };
        /** @default null */
        GenerateScreensResponse: {
            reply?: string;
            screens?: components["schemas"]["GeneratedScreen"][];
            /**
             * @description Screens the model proposed that this API could not read at all.
             * @default
             */
            skipped: string[];
            usage?: components["schemas"]["AiUsageView"];
        };
        /** @default null */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** @default null */
        LoginResponse: {
            /** Format: date-time */
            expiresAt?: string;
            /**
             * @description Send as `Authorization: Bearer <token>`.
             * @default
             */
            token: string;
            user?: components["schemas"]["UserView"];
        };
        /** @default null */
        MeetingCreate: {
            attendees?: string;
            /** Format: date */
            date: string;
            id?: string;
            /** @enum {string} */
            kind?: "meeting-note" | "wireframe";
            notes?: string;
            postedBy?: string;
            /** @enum {string} */
            source?: "meeting" | "feedback" | "suggestion";
            title: string;
        };
        /**
         * @description Only the fields present are changed.
         * @default null
         */
        MeetingUpdate: {
            attendees?: string;
            /** Format: date */
            date?: string;
            /** @enum {string} */
            kind?: "meeting-note" | "wireframe";
            notes?: string;
            postedBy?: string;
            /**
             * @description Id of the product to build into; empty string clears it.
             * @default
             */
            productId: string;
            /** @enum {string} */
            source?: "meeting" | "feedback" | "suggestion";
            title?: string;
        };
        /** @default null */
        MeetingView: {
            attendees?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date */
            date?: string;
            id?: string;
            /** @enum {string} */
            kind?: "meeting-note" | "wireframe";
            /**
             * @description The product they have actually been sent to. A fact.
             * @default
             */
            movedTo: components["schemas"]["ProjectRef"];
            notes?: string;
            postedBy?: string;
            /**
             * @description The product these screens are built to fit. A plan.
             * @default
             */
            product: components["schemas"]["ProjectRef"];
            projectId?: string;
            screens?: components["schemas"]["ScreenView"][];
            /** @enum {string} */
            source?: "meeting" | "feedback" | "suggestion";
            title?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /**
         * @description Where a screen was agreed to sit, as the path it was agreed at. Kept as a path rather than a reference because the parent may not be in this product yet.
         * @default null
         */
        Placement: {
            parentName?: string;
            parentPath?: string[];
            /** @enum {string} */
            platform?: "PC" | "Mobile";
            /** @enum {string} */
            screenType?: "Screen" | "Popup" | "Drawer";
        };
        /** @default null */
        ProjectCreate: {
            archived?: boolean;
            customer?: string;
            /**
             * @description Supplied when the client already named it; generated otherwise.
             * @default
             */
            id: string;
            name: string;
            owner?: string;
            summary?: string;
        };
        /**
         * @description Just enough of a project to name it.
         * @default null
         */
        ProjectRef: {
            id?: string;
            name?: string;
        };
        /**
         * @description Only the fields present are changed.
         * @default null
         */
        ProjectUpdate: {
            accent?: string;
            archived?: boolean;
            customer?: string;
            name?: string;
            owner?: string;
            solution?: string;
            spend?: number;
            stage?: string;
            statusLabel?: string;
            statusTone?: string;
            summary?: string;
        };
        /**
         * @description A project of either kind; archived means Customer.
         * @default null
         */
        ProjectView: {
            accent?: string;
            archived?: boolean;
            /** Format: date-time */
            createdAt?: string;
            customer?: string;
            id?: string;
            name?: string;
            owner?: string;
            solution?: string;
            spend?: number;
            stage?: string;
            statusLabel?: string;
            statusTone?: string;
            summary?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @default null */
        RequestCreate: {
            fromLabel?: string;
            /**
             * @description The copy's own id. Generated when absent.
             * @default
             */
            id: string;
            name: string;
            placement?: components["schemas"]["Placement"];
            route?: string;
        };
        /**
         * @description Filing a waiting request into a round.
         * @default null
         */
        RequestFile: {
            /** Format: int32 */
            version: number;
        };
        /**
         * @description Moving a set of screens into a product. A screen whose name already waits from the same source replaces that row rather than joining it.
         * @default null
         */
        RequestMove: {
            screens: components["schemas"]["RequestCreate"][];
        };
        /**
         * @description A screen waiting in a product for a round.
         * @default null
         */
        RequestView: {
            /** Format: date-time */
            createdAt?: string;
            fromLabel?: string;
            id?: string;
            /** Format: date-time */
            movedAt?: string;
            name?: string;
            placement?: components["schemas"]["Placement"];
            projectId?: string;
            route?: string;
            /**
             * Format: int32
             * @description The round it was filed into; null while it is still waiting.
             * @default
             */
            version: number;
            waiting?: boolean;
        };
        /** @default null */
        ScreenHtml: {
            html: string;
        };
        /**
         * @description Records that the set has been sent to a product.
         * @default null
         */
        ScreensMoved: {
            projectId: string;
        };
        /**
         * @description The whole set after a generation. Screens matched by name keep their id, their placement and their moved mark; the rest are new.
         * @default null
         */
        ScreensReplace: {
            screens: components["schemas"]["ScreenWrite"][];
        };
        /**
         * @description A screen without its page. The html is fetched per screen, because a meeting's pages together run to megabytes.
         * @default null
         */
        ScreenView: {
            /**
             * @description `new` when the product has never had it, `modified` when it changed since it was sent, null when they agree.
             * @default
             * @enum {string}
             */
            change: "new" | "modified";
            id?: string;
            /** Format: date-time */
            movedAt?: string;
            name?: string;
            parentId?: string;
            /** @enum {string} */
            platform?: "PC" | "Mobile";
            /** Format: int32 */
            position?: number;
            /** @enum {string} */
            screenType?: "Screen" | "Popup" | "Drawer";
            /** Format: date-time */
            updatedAt?: string;
        };
        /**
         * @description One generated screen. `parentId` may name another screen in the same request; parents need not be listed first.
         * @default null
         */
        ScreenWrite: {
            html?: string;
            id?: string;
            name: string;
            parentId?: string;
            /** @enum {string} */
            platform?: "PC" | "Mobile";
            /** @enum {string} */
            screenType?: "Screen" | "Popup" | "Drawer";
        };
        /**
         * @description Who the caller is, as the workspace shows them.
         * @default null
         */
        UserView: {
            department?: string;
            email?: string;
            id?: string;
            /** Format: date-time */
            lastLoginAt?: string;
            name?: string;
            roles?: string[];
            usageGroup?: string;
        };
        /**
         * @description A batch of writes, applied together. The browser batches its changes and sends them as one request rather than one per key.
         * @default null
         */
        WorkspaceStatePatch: {
            entries: components["schemas"]["WorkspaceStateWrite"][];
        };
        /** @default null */
        WorkspaceStateResult: {
            /** Format: int32 */
            deleted?: number;
            rejected?: string[];
            /** Format: int32 */
            written?: number;
        };
        /**
         * @description Everything the caller can see, as one map. Read once when the workspace loads, because the code that consumes it reads synchronously.
         * @default null
         */
        WorkspaceStateSnapshot: {
            /**
             * @description Key to the exact string that was stored.
             * @default
             */
            entries: {
                [key: string]: string;
            };
            /**
             * @description Keys that belong to this viewer rather than the team.
             * @default
             */
            personalKeys: string[];
        };
        /**
         * @description One key to write, or to delete when `value` is null.
         * @default null
         */
        WorkspaceStateWrite: {
            key: string;
            /**
             * @description The string to store. Null deletes the key.
             * @default
             */
            value: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    toWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    canvas: {
        parameters: {
            query?: never;
            header?: {
                "X-Anthropic-Api-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CanvasEditRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CanvasEditResponse"];
                };
            };
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: {
                /** @description Spend your own quota instead of the server's. */
                "X-Anthropic-Api-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description A stream of envelopes: `stream_event` per token, then a closing `result`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": string;
                };
            };
        };
    };
    frd: {
        parameters: {
            query?: never;
            header?: {
                "X-Anthropic-Api-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrdRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FrdResponse"];
                };
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: {
                "X-Anthropic-Api-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateScreensRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GenerateScreensResponse"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AiStatus"];
                };
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: {
                "X-Anthropic-Api-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AiVerifyResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserView"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeetingView"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeetingView"];
                };
            };
        };
    };
    replaceScreens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreensReplace"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeetingView"];
                };
            };
        };
    };
    reset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeetingView"];
                };
            };
        };
    };
    markMoved: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreensMoved"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeetingView"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectView"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectView"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectView"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectView"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeetingView"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeetingView"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                waitingOnly?: boolean;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RequestView"][];
                };
            };
        };
    };
    move: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestMove"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RequestView"][];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestFile"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RequestView"];
                };
            };
        };
    };
    html: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScreenHtml"];
                };
            };
        };
    };
    saveHtml: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreenHtml"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScreenView"];
                };
            };
        };
    };
    snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceStateSnapshot"];
                };
            };
        };
    };
    apply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceStatePatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceStateResult"];
                };
            };
        };
    };
    importMissing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceStatePatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceStateResult"];
                };
            };
        };
    };
}
