'use client';

/**
 * A design file opened for editing, as the page it is.
 *
 * This replaced the block canvas. The canvas was the right surface while a
 * design was *made* of blocks, but every screen that now arrives here — a
 * customer task moved across, a page generated by the chat — is a document,
 * and a document edited through a block schema loses whatever the schema has
 * no word for. Block-native files still open here: `resolveScreenHtml` renders
 * their blocks into a document first.
 *
 * The workspace layout keeps the project nav and the file tree on screen; only
 * this pane changes.
 */

import { ArrowLeft, Code2, MonitorPlay } from 'lucide-react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { Suspense, useEffect, useState } from 'react';
import { Badge, Button } from '@/components/ui';
import { useBusinessWorkspace } from '@/components/we-adk/business-workspace';
import { PageEditor } from '@/components/we-adk/page-editor';
import { businessEditHref, businessPreviewHref } from '@/components/we-adk/mockup-board';
import { PreviewEditTabs } from '@/components/we-adk/screen-preview';
import { isHtmlDesignFile } from '@/lib/we-adk/design-html';
import { findPrototypeFile } from '@/lib/we-adk/prototype';
import { resolveScreenHtml, saveScreenHtml } from '@/lib/we-adk/screen-html';
import { resolveScreen, type ResolvedScreen } from '@/lib/we-adk/screen-registry';

function BusinessEditPane() {
  const { project, folders, isReleased } = useBusinessWorkspace();
  const searchParams = useSearchParams();
  const screenId = searchParams.get('screen');
  const folderId = searchParams.get('folder');

  const file = screenId
    ? folders
        .flatMap((folder) => [...folder.files, ...(folder.children ?? []).flatMap((c) => c.files)])
        .find((entry) => entry.id === screenId)
    : undefined;

  // A link can point at a design outside this project's tree; resolve it anyway
  // so the header names what it is showing instead of an id.
  const [elsewhere, setElsewhere] = useState<ResolvedScreen | null>(null);
  useEffect(() => {
    setElsewhere(!screenId || file ? null : resolveScreen(screenId, project.id));
  }, [screenId, file, project.id]);

  /*
   * The page can only be read after mount, and only once: handing `PageEditor`
   * a value that changes identity would reset its history and its selection.
   */
  const [html, setHtml] = useState<string | null | undefined>(undefined);

  const prototype = screenId ? findPrototypeFile(screenId) : null;
  const screenName = prototype?.name ?? file?.name ?? elsewhere?.name ?? screenId ?? '';
  const screenRoute = prototype?.route ?? file?.route ?? elsewhere?.route;
  const round = folders
    .flatMap((folder) => [folder, ...(folder.children ?? [])])
    .find((folder) => folder.id === folderId);
  const releasedRound = round ? round.versionStatus === 'Released' : isReleased;

  useEffect(() => {
    if (!screenId) return;
    setHtml(
      resolveScreenHtml({
        screenId,
        name: screenName,
        seedPattern: file?.seedPattern,
        route: screenRoute,
        origin: round?.name,
      }),
    );
    // Deliberately keyed on the screen alone. The name and round are only used
    // to title the rendered document, and re-resolving on every change to them
    // would throw away edits in progress.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [screenId]);

  if (!screenId) {
    return (
      <div className="text-muted-foreground flex min-w-0 flex-1 items-center justify-center text-sm">
        Pick a design file to edit.
      </div>
    );
  }

  const header = (
    <div className="bg-background flex shrink-0 items-center gap-2 border-b px-4 py-2">
      <Button variant="ghost" size="sm" className="h-7 gap-1 px-2 text-xs" asChild>
        <Link href={businessPreviewHref(project.id, screenId, folderId)}>
          <ArrowLeft className="size-3" />
        </Link>
      </Button>
      {prototype ? (
        <Code2 className="text-muted-foreground size-3.5 shrink-0" />
      ) : (
        <MonitorPlay className="text-muted-foreground size-3.5 shrink-0" />
      )}
      <span className="truncate font-mono text-xs font-medium">{screenName}</span>
      {screenRoute && <span className="text-muted-foreground truncate text-xs">{screenRoute}</span>}
      {!isHtmlDesignFile(screenId, file?.fileName) && (
        <Badge variant="outline" className="shrink-0 text-[10px]">
          wireframe
        </Badge>
      )}
      <div className="ml-auto">
        <PreviewEditTabs
          active="edit"
          released={releasedRound}
          previewHref={businessPreviewHref(project.id, screenId, folderId)}
          editHref={businessEditHref(project.id, screenId, folderId)}
        />
      </div>
    </div>
  );

  /*
   * A released round is a record of what shipped, so it is not editable. The
   * tab pair hides itself for one, but a link straight to this route would
   * still land here.
   */
  if (releasedRound) {
    return (
      <div className="flex min-w-0 flex-1 flex-col">
        {header}
        <div className="text-muted-foreground flex flex-1 items-center justify-center px-8 text-center text-sm">
          {screenName} is in a released round, so it cannot be edited. Open it in Preview, or
          copy it into the round in progress.
        </div>
      </div>
    );
  }

  return (
    <div className="flex min-w-0 flex-1 flex-col">
      {header}
      {html === undefined ? (
        <div className="text-muted-foreground flex flex-1 items-center justify-center text-sm">
          Loading the page…
        </div>
      ) : html === null ? (
        <div className="text-muted-foreground flex flex-1 items-center justify-center px-8 text-center text-sm">
          This file has nothing on it yet. Generate a screen for it from a task, or ask the chat
          beside its preview to build one.
        </div>
      ) : (
        <PageEditor
          key={screenId}
          html={html}
          screenTitle={screenName}
          onSave={(next) => saveScreenHtml(screenId, next)}
        />
      )}
    </div>
  );
}

export default function BusinessEditPage() {
  return (
    <Suspense
      fallback={
        <div className="text-muted-foreground flex flex-1 items-center justify-center text-sm">
          Loading the page…
        </div>
      }
    >
      <BusinessEditPane />
    </Suspense>
  );
}
