import { Card, CardContent, Progress } from '@/components/ui';
import { UNIT_TESTS } from '@/lib/we-adk-mock/builder';

export default function UnitTestsPage() {
  return (
    <div className="flex flex-col gap-4">
      <h1 className="text-lg font-semibold">Unit tests</h1>
      <p className="text-muted-foreground text-sm">
        Unit test results generated by the Developer harness alongside the implementation.
      </p>
      <div className="flex flex-col gap-2">
        {UNIT_TESTS.map((suite) => (
          <Card key={suite.suite} className="gap-0 py-0">
            <CardContent className="flex items-center gap-4 px-4 py-3">
              <div className="min-w-0 flex-1">
                <p className="font-medium">{suite.suite}</p>
                <p className="text-muted-foreground text-xs">
                  {suite.passed}/{suite.cases} cases passed · {suite.coverage}% coverage
                </p>
              </div>
              <div className="w-40">
                <Progress value={suite.coverage} />
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
