import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui';
import { StatusChip } from '@/components/we-adk/status-chip';
import { SCREEN_DESIGNS } from '@/lib/we-adk-mock/builder';

export default function ScreenDesignsPage() {
  return (
    <div className="flex flex-col gap-4">
      <h1 className="text-lg font-semibold">Screen designs</h1>
      <p className="text-muted-foreground text-sm">
        Auto-generated by AI once Developer finishes implementation, based on the real component
        structure.
      </p>
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Screen path</TableHead>
            <TableHead>Component</TableHead>
            <TableHead>Status</TableHead>
            <TableHead>Updated</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {SCREEN_DESIGNS.map((row) => (
            <TableRow key={row.path}>
              <TableCell className="font-medium">{row.path}</TableCell>
              <TableCell className="text-muted-foreground font-mono text-xs">
                {row.component}
              </TableCell>
              <TableCell>
                <StatusChip {...row.status} />
              </TableCell>
              <TableCell className="text-muted-foreground">{row.updatedAt}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
